services:
  - type: web
    name: railfast-tatkal
    env: docker
    region: singapore
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
